package main

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
)

const (
	manifestName    = "wowbak-manifest.json"
	manifestVersion = 1
	payloadRoot     = "data"
)

// Directories Blizzard creates per game version. A flavor dir holds Interface/AddOns and WTF.
var knownFlavors = []string{
	"_retail_", "_classic_", "_classic_era_", "_ptr_", "_xptr_", "_beta_",
	"_classic_ptr_", "_classic_era_ptr_", "_classic_beta_",
}

// Backed-up roots inside a flavor dir.
var scanRoots = []string{"Interface/AddOns", "WTF"}

// A pattern with no "/" matches a basename; "**/" or "*/" matches a basename at any
// depth; anything else matches the whole flavor-relative path.
var defaultExcludes = []string{
	".git", ".svn", ".DS_Store", "Thumbs.db", "desktop.ini",
	"*.lua.bak",           // SavedVariables backups, regenerated by the client
	"*.wowbak-removed",    // addons a previous --clean set aside
	"**/config-cache.wtf", //
	"WTF/Config.wtf",      // resolution + hardware settings, machine specific
}

type FileMeta struct {
	Size   int64  `json:"size"`
	MTime  int64  `json:"mtime"`
	SHA256 string `json:"sha256"`
}

type AddonMeta struct {
	Version   string `json:"version"`
	Interface string `json:"interface"`
	Title     string `json:"title"`
	Files     int    `json:"files"`
	Bytes     int64  `json:"bytes"`
	Digest    string `json:"digest"`
}

type WTFMeta struct {
	Accounts []string `json:"accounts"`
	Files    int      `json:"files"`
	Bytes    int64    `json:"bytes"`
	Digest   string   `json:"digest"`
}

type Totals struct {
	Files int   `json:"files"`
	Bytes int64 `json:"bytes"`
}

type FlavorData struct {
	Addons map[string]AddonMeta `json:"addons"`
	WTF    WTFMeta              `json:"wtf"`
	Files  map[string]FileMeta  `json:"files"`
	Totals Totals               `json:"totals"`
}

type Source struct {
	OS          string `json:"os"`
	Platform    string `json:"platform"`
	Hostname    string `json:"hostname"`
	InstallPath string `json:"install_path"`
}

type Manifest struct {
	ManifestVersion int                    `json:"manifest_version"`
	Tool            string                 `json:"tool"`
	CreatedUTC      string                 `json:"created_utc"`
	Source          Source                 `json:"source"`
	Note            string                 `json:"note,omitempty"`
	Excludes        []string               `json:"excludes"`
	FollowSymlinks  bool                   `json:"follow_symlinks"`
	Flavors         map[string]*FlavorData `json:"flavors"`
}

// sortedFlavors keeps output deterministic; Go map order is not.
func sortedFlavors(m map[string]*FlavorData) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Slice(out, func(i, j int) bool { return flavorRank(out[i]) < flavorRank(out[j]) })
	return out
}

func flavorRank(name string) int {
	for i, f := range knownFlavors {
		if f == name {
			return i
		}
	}
	return len(knownFlavors)
}

// ---------------------------------------------------------------- install path

func expandHome(p string) string {
	if p == "~" || strings.HasPrefix(p, "~/") || strings.HasPrefix(p, `~\`) {
		if home, err := os.UserHomeDir(); err == nil {
			return filepath.Join(home, p[1:])
		}
	}
	return p
}

func candidateInstalls() []string {
	home, _ := os.UserHomeDir()
	switch runtime.GOOS {
	case "windows":
		var out []string
		for _, root := range []string{
			`C:\Program Files (x86)`, `C:\Program Files`,
			`D:\`, `D:\Games`, `E:\Games`, `C:\Games`,
			filepath.Join(home, "Games"),
		} {
			out = append(out, filepath.Join(root, "World of Warcraft"))
		}
		return out
	case "darwin":
		return []string{
			"/Applications/World of Warcraft",
			filepath.Join(home, "Applications", "World of Warcraft"),
		}
	default:
		return []string{
			filepath.Join(home, "Games/world-of-warcraft/drive_c/Program Files (x86)/World of Warcraft"),
			filepath.Join(home, ".wine/drive_c/Program Files (x86)/World of Warcraft"),
			filepath.Join(home, "Games/battlenet/drive_c/Program Files (x86)/World of Warcraft"),
		}
	}
}

func isDir(p string) bool {
	st, err := os.Stat(p)
	return err == nil && st.IsDir()
}

func looksLikeInstall(p string) bool {
	for _, f := range knownFlavors {
		if isDir(filepath.Join(p, f)) {
			return true
		}
	}
	return false
}

// resolveInstall: --install-path beats WOWBAK_INSTALL_PATH beats config beats autodetection.
func resolveInstall(explicit string) string {
	sources := []struct{ label, value string }{
		{"--install-path", explicit},
		{"WOWBAK_INSTALL_PATH", os.Getenv("WOWBAK_INSTALL_PATH")},
		{"config", loadConfig().InstallPath},
	}
	for _, s := range sources {
		if s.value == "" {
			continue
		}
		abs, err := filepath.Abs(expandHome(s.value))
		if err != nil {
			fatalf("bad path from %s: %v", s.label, err)
		}
		if !isDir(abs) {
			fatalf("install path from %s does not exist: %s", s.label, abs)
		}
		if !looksLikeInstall(abs) {
			fatalf("install path from %s has no game version dirs (%s, ...): %s",
				s.label, strings.Join(knownFlavors[:3], ", "), abs)
		}
		return abs
	}
	for _, p := range candidateInstalls() {
		if isDir(p) && looksLikeInstall(p) {
			abs, _ := filepath.Abs(p)
			return abs
		}
	}
	fatalf("no WoW install found. Set one with:\n" +
		"  wowbak config set install_path \"C:\\path\\to\\World of Warcraft\"\n" +
		"The path is the folder containing _retail_ / _classic_era_ / etc.")
	return ""
}

func presentFlavors(install string) []string {
	var out []string
	for _, f := range knownFlavors {
		if isDir(filepath.Join(install, f)) {
			out = append(out, f)
		}
	}
	return out
}

func resolveFlavors(install string, requested []string) []string {
	present := presentFlavors(install)
	if len(requested) > 0 {
		var missing []string
		for _, r := range requested {
			if !contains(present, r) {
				missing = append(missing, r)
			}
		}
		if len(missing) > 0 {
			avail := "(none)"
			if len(present) > 0 {
				avail = strings.Join(present, ", ")
			}
			fatalf("flavor(s) not present in %s: %s\navailable: %s",
				install, strings.Join(missing, ", "), avail)
		}
		return requested
	}
	if cfg := loadConfig(); len(cfg.Flavors) > 0 {
		var out []string
		for _, f := range cfg.Flavors {
			if contains(present, f) {
				out = append(out, f)
			}
		}
		return out
	}
	return present
}

func contains(list []string, s string) bool {
	for _, v := range list {
		if v == s {
			return true
		}
	}
	return false
}

// fatalError is what fatalf panics with. The CLI turns it back into exit code 2;
// the GUI's job runner recovers it and fails that one job instead of taking the
// whole server down.
type fatalError struct{ msg string }

func (e fatalError) Error() string { return e.msg }

func fatalf(format string, args ...any) {
	panic(fatalError{msg: fmt.Sprintf(format, args...)})
}

func human(n int64) string {
	f := float64(n)
	for _, unit := range []string{"B", "KB", "MB", "GB"} {
		if f < 1024 || unit == "GB" {
			if unit == "B" {
				return fmt.Sprintf("%.0f B", f)
			}
			return fmt.Sprintf("%.1f %s", f, unit)
		}
		f /= 1024
	}
	return ""
}
